var quotes = [
  "Asking the wrong questions is more important than providing the right answers",
  "We speak about death even when we don't",
  "We are fragile opinions surrounded by hostile facts.",
  "Ideas are born in light and out of light, but they grow in darkness, feeding on darkness.",
  "Progress is progress for the ones who make it and sell it, but not for the ones who never asked for it and are now forced to accept it and buy it",
  "The most difficult part of finding a solution is to accept that there is a problem",
  "The most difficult part of a problem is always to understand what the problem is",
  "The history of human civilization can be rewritten as the history of making humans dumber and then inventing smarter tools tor dumber humans",
  "The history of science is, by definition, a chronological record of past mistakes",
  "To be or not to be? should be rephrased as two complementary questions: Is it possible to be? and Is it possible not to be?",
  "You are located not where you are but what you are.",
  "If an animal spread plastic garbage all over the planet, we would certainly exterminate it. ",
  "Luckily, Nature is much more exciting than Science makes it look like; and luckily Science is much more exciting than Nature makes it look like.",
  "Games play people",
  "You are not what you do but what you allow others to do to you",
  "The history of the world in a nutshell: the luxuries of the previous generation become the necessities of the new generation.",
  "We never fully wake up.",
  "Poetry is the art of turning the obvious into the mysterious. ",
  "A helmet is not a replacement for a brain",
  "Gods are software, and, like all software, they have bugs.",
  "Is what I learn from there worth what I forget about here?",
  "You are a grammatical construct: do not misspell yourself.",
  "Like a word in a sentence, the company that you keep determines what you are: a verb, a noun, an adjective, an article, ..., or a punctuation mark. ",
  "We have more money to spend in our spare time but not more time in which to spend it therefore time is increasingly more valuable than money",
  "Philosophy is the art of saying something incredibly stupid and making it sound incredibly intelligent.",
  "The irony of the human condition is that there are no answers: each answer is, in reality, a new question. ",
  "Science is often an excuse for not thinking",
  "It is rational not to be rational. It would be irrational to be rational. Only very irrational people are rational.",
  "The way we teach morality to children, by reward and punishment, is not very moral",
  "Each of us is the product of all the mistakes made by previous generations",
  "We say hello more often than we say goodbye, but we say goodbye much better than we say hello.",
  "Question answers instead of answering questions.",
  "Public opinion is public ignorance.",
  "I wish i could tell you what to do but what to do is not to let people tell you what to do.",
  "Complexity is a simple concept to understand, and simplicity is a very complex concept.",
  "Becoming mature adults is about practicing deceit to the point that we don't remember what we are deceiving ourselves about",
  "The universe is a pointless distraction",
  "No matter how far you walk the distance remains the same.",
  "The 'I' watches the 'me' live, and the 'me' watches the 'I' die.",
  "Someone should invent a new science to study imaginary problems. And the real problems caused by their solutions.",
  "Real beings dream unreal worlds. Do unreal beings dream the real world?",
  "Death is a mystery only for those who are alive.",
  "The law of entropy leads us to fight against our fate instead of accepting it, and that's the history of humankind",
  "The history of the human race is a history of increasing dependence of society on a new technology with unpredictable side effects that end up requiring the creation of, and the increasing dependence on, a new technology",
  "Anybody who claims to understand science does not understand science",
  "Humans want to build machines that think like humans while machines are already building humans who think like machines",
  "It is the pursuit of happiness that makes people unhappy.",
  "Marriage is the art of having two people work together to solve problems that, alone, neither would have.",
  "The paradox of innovation is that it is accepted as an innovation when it has become imitation.",
  "As we live, we talk less and less about the things we really care about because we learn that that is not what life is about",
  "Ideology is a study of causes, not of effects.",
  "Good can only triumph over Evil by employing extreme evil, thereby fulfilling the mission of Evil",
  "Life was obviously invented by a dead person",
  "It's not about where you are but about who's around you.",
  "The present always feels premature even though the future is often overdue",
  "The only thing that is worse than not finding the solution to a problem is to find the right solution to the wrong problem",
  "Only by mourning our impotence can we assert our power",
  "It is cool to behave different only when everybody else is behaving that way.",
  "Loneliness is a cancer only if you let it grow. Taken in small doses, it is the most powerful medicine, the only one that can resurrect you.",
  "The choice is not between being philosopher or not being philosophers, it's about being good or bad philosophers",
  "Let us not pretend otherwise: we are surrounded",
  "We are swimming in the lake in which future generations will drown",
  "I am both the hiker and the trail",
  "Most difficult is making sense of other people because they are trying to make sense of me, so the sense changes all the time",
  "Fear of the world created the gods that created the world that we fear",
  "Certainty is a by-product of confusion",
  "If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a marketing commercial to sell ducks",
  "You are a question that is never asked",
  "One of the most difficult (and consequential) things in life is figuring out whether a question is stupid or not",
  "You are the people with whom you surround yourself. Make sure you want to be them",
  "Question everything because everything questions you",
  "Human civilization is the story of turning the impossible into the inevitable",
  "If the question is me, the answer is you",
  "Machines must be understood not programmed",
  "We are not what we are. Now the question is: are we what we are not?",
  "It is very difficult to resist the temptation to think that the future will be exactly like the past even though the future has never been like the past",
  "If i am stupid, i am not intelligent enough to realize it",
  "Beauty is everywhere. Unfortunately, we are nowhere.",
  "Thinking about nothing makes it something. Thinking about something makes it nothing",
  "High-tech has become the discipline of complicating simple things",
  "It is cool to behave different only when everybody else is behaving that way",
  "'Only when the tide recedes do you find out who's been swimming naked' (Warren Buffet). 'We're all naked' (piero)",
  "The world is divided into the ordinary and the extraordinary. The problem is deciding which is which.",
  "Physics is an illusion. What it reveals is the structure of our brain, not the structure of the universe.",
  "What we understand is not enough to understand why we understand it",
  "'A man is infinitely more complicated than his thoughts' (Paul Valery) 'A man is infinitely more complicated than his actions' (piero)",
  "The success of most high-tech projects depends not on making smarter technology but on making dumber users",
  "Since we came to this world we only heard lies. But it's the lies that make it interesting. The truth would devastate us",
  "Computer science is becoming the discipline of turning your life into somebody else's business opportunity",
  "The living beings that have the longest life expectancy are those that have no brain: trees and bacteria",
  "The most powerful knowledge is the knowledge that induces people to radically change their concept of what knowledge is",
  "A man is infinitely more complicated than his actions; a woman is infinitely more complicated than her words" ,
  "The only reason that things get occasionally done is that we misunderstand each other all the time",
  "Destiny is what you don't understand until it happens.",
  "Fundamentally, communism was a blessing to capitalism because it created so much poverty for capitalists to exploit.",
  "Success in solving a set of problems inevitably creates a new set of problems, and a system that is incapable of solving the new set of problems.",
  "We are not training machines to become like humans but humans to become like machines.",
  "The severity of a problem increases exponentially with the time it takes to realize that the severity of a problem increases exponentially with the time it takes to realize that the severity of a problem increases exponentially with the time it takes...",
  "The only way to know what i know is to know what i don't know",
  "We keep changing the question but the answer remains the same",
  "The world is simpler than the brain that conceives it",
  "A comedian is someone who tells the truth. Truth is the set of all jokes told by all comedians in the world.",
  "The next time you say forever think of never",
  "Each of us is a lifelong project to build a coherent theory on top of a blatant contrdiction",
  "History is the impossible becoming inevitable.",
  "The part is the sum of its wholes.",
  "Knowledge is overrated, truth is underrated.",
  "Philosophy is the art of turning solutions into problems",
  "We think we know where we live, but we only live where we know.",
  "We are what we find, not what we search for.",
  "Beauty is not in the eye of the beholder but in the mind of the thinker.",
  "Great civilizations are those that do NOT learn from the mistakes of past civilizations",
  "Very few things are inevitable in life, not even life itself.",
  "Intelligence is not about knowing the answers but about asking the questions",
  "Bureaucracy is often a problem, rarely a solution.",
  "The best books are those you don't want to finish reading because you hate the idea that they will end",
  "Nature is a poet that never uses the word 'I'",
  "What we are today is a special case of what we will be tomorrow",
  "Thankfully we cannot understand the universe",
  "The glitch is the rhythm",
  "Demagogy leads to bigger disasters than the ones it promised to prevent.",
  "Life is about finding solutions to solvable problems. What is more interesting is finding solutions to unsolvable problems.",
  "We always underestimate the ingenuity of idiots",
  "If you disagree with yourself, you are always right.",
  "If we thought more highly of ourselves, we would not watch bad films and read bad books just because they are publicized ",
  "A revolution is started by people who don't have what they want and hijacked by people who don't want what they have",
  "What is one expected to expect?",
  "The first step to finding a solution is to admit that there is a problem",
  "I see everything everywhere",
  "Am I myself?",
  "There is a limit to human intelligence, but there is no limit to human stupidity",
  "Life is not a journey, it is a destination",
  "There is nothing more dangerous than a philosopher who wants to change the world",
  "Life is a question in the form of an answer",
  "The more familiar I get with the universe, the less familiar I feel with myself",
  "Aging is a voyage of the mind through its body as it learns how many organs have to work in order to keep it alive.",
  "People tend to talk about what people tend to talk about",
  "Any prolonged aesthetic theory eventually becomes a distraction rather than an attraction.",
  "Cogito. Ergo I am feasible.",
  "I do not think thoughts, thoughts think me.",
  "Most books are about aspects of human knowledge. Few people write books about human ignorance, despite the fact that there would be much more to write about.",
  "If you can't always get what you want, may you always want what you get",
  "Questions are more important than answers",
  "We are not Nature's only experiment, but we may be one of the few that will fail",
  "Every point in the universe is a solution to an equation",
  "In the age of globalization, we are all illiterate",
  "A fundamental property of life is the ability to predict the future.",
  "The thinker is created by thought",
  "It only make sense to write/ of what one knows nothing of",
  "Most of political history is a story of very stupid individuals doing very stupid things that are sold to future generations as heroic ",
  "I do not envy God",
  "Asking the wrong questions is more important than providing the right answers. August 24, 2016",
  "We are fragile opinions surrounded by hostile facts. June 6, 2016",
  "The problem is always to understand what the problem is. may 28, 2016",
  "The history of human civilization can be rewritten as the history of making humans dumber and then inventing smarter tools tor dumber humans. May 18, 2016",
  "The history of science is, by definition, a chronological record of past mistakes. May 11, 2016",
  "To be or not to be? should be rephrased as two complementary questions: Is it possible to be? and Is it possible not to be?. May 9, 2016",
  "Question answers instead of answering questions. Apr 10, 2016",
  "We mostly hide in places where everybody can see us. Mar 8, 2016.",
  "You are located not where you are but what you are. Jan 12, 2016",
  "If an animal spread plastic garbage all over the planet, we would certainly exterminate it. Nov 30, 2015",
  "Luckily, Nature is much more exciting than Science makes it look like; and luckily Science is much more exciting than Nature makes it look like. November 3, 2015",
  "You are not what you do but what you allow others to do to you. October 20, 2015",
  "Dumb boring people use Facebook to post comments that show how smart and funny they are. July 15, 2015",
  "The best memory is the one that forgets everything. May 12, 2015.",
  "We never fully wake up. Mar 20, 2015",
  "Things that Satan praises in the Jewish/Christian/Muslim books: democracy, gender equality, capitalism, science, sex, education, science,fun Mar 19, 2015",
  "Poetry is the art of turning the obvious into the mysterious. Feb 3, 2015",
  "What a viewer views in a painting is actually not the light that the painting absorbs/likes but the light that the painting reflects/dislikes. Jan 26,2015",
  "Gods are software, and, like all software, they have bugs. Jan 17, 2015.",
  "You are a grammatical construct: do not misspell yourself. Jan 7, 2015",
  "You can be a verb, a noun, an adjective, an article etc or a punctuation mark. The company you keep determines what you are. Jan 7, 2015",
  "When people talk about survival of the fittest, what exactly do they mean by survival? Jan 5, 2015",
  "The irony of the human condition is that there are no answers: each answer is, in reality, a new question. December 6, 2014",
  "Only those trained to see the invisible can comprehend the visible. November 6, 2014",
  "People's attention span is becoming so short that it will soon be impossible to explain the consequences of a short attention span. November 4, 2014",
  "Science is often an excuse for not thinking, and a scientist is often not a thinker. Worse of all is the science of thought, neuroscience.",
  "It is rational not to be rational. It would be irrational to be rational. Only very irrational people are rational. October 26, 2014",
  "The way we teach morality to children, by reward and punishment, doesn't seem very moral to me. September 18, 2014",
  "Each of us is the product of all the mistakes made by previous generations. September 4, 2014.",
  "We say hello more often than we say goodbye, but we say goodbye much better than we say hello. September 1, 2014",
  "People who live ordinary lives crave for extraordinary ones, and people who live extraordinary lives crave for ordinary ones. August 2, 2014",
  "Public opinion is public ignorance, July 11, 2014",
  "Complexity is a simple concept to understand, and simplicity is a very complex concept. June 26, 2014",
  "I wish i could tell you what to do but what to do is not to let people tell you what to do. June 24, 2014",
  "Becoming mature adults is about practicing deceit to the point that we don't remember what we are deceiving ourselves about. Apr 26, 2014",
  "God to moses in the Bible: I am who i am. Iago in Shakespeare's Othello: I am not what i am. Iago is way more interesting than God. Apr 13, 2014",
  "The universe is a pointless distraction. Apr 12, 2014",
  "Life is a transition from the I to the me and back to the I, who watches the me live, and back to the me, who watches the I die. Apr 1, 2014",
  "Your identity, dignity and privacy are the collateral damage of any business plan based on advertising revenues",
  "Nothing has killed more people than religion, and, still, all religious people claim that their religion is about peace. Mar 10, 2014",
  "The landscape provides us with the tools that we use to shape the landscape Feb 25, 2014",
  "Between here and now is me. February 14, 2014.",
  "Death is a mystery only for those who are alive. January 29, 2014",
  "The law of entropy leads us to fight against our fate instead of accepting it, and that's the history of humankind. January 28, 2014",
  "Anybody who claims to understand science does not understand science. January 23, 2014",
  "Are we mapping the territory or is the territory mapping us? January 19, 2014",
  "Humans want to build machines that think like humans while machines are already building humans who think like machines. January 16, 2014",
  "The less you know about the past the more likely you are to be amazed by the present. January 14, 2014",
  "I do not exist but my existence is. January 11, 2013",
  "The fact that you exist is proof that you are an incredibly lucky person: the chances of you being born were almost zero.",
  "I think people who write programs do have at least a glimmer of extra insight into the nature of God... because creating a program often means that you have to create a small universe (Don Knuth)",
  "Computing creates new sacred spaces, rituals, myths. October 25, 2013",
  "We are a species obsessed with the future. We are also the species that is fully aware of death, i.e. that there is no future. September 28, 2013",
  "Memories of the future are sometimes more accurate than memories of the past,because we have a vested motivation to keep changing the past. August 9, 2013",
  "The meaning of life is addiction. If you are not addicted to something, you probably already committed suicide. July 15, 2013",
  "They waited for millions of years for us to arrive. Now they are just waiting for us to go away. June 20, 2013",
  "As we live, we talk less and less about the things we really care about because we learn that that is not what life is about. June 14, 2013",
  "Life is a Post Scriptum and it's a very short one. June 13, 2013",
  "An individual is more likely to behave irrationally when in a group than when he's alone, and there must be an evolutionary reason for it. June 1, 2013",
  "Starting with conception, the truly important events of our life are decided by others: why is it called my life? May 28, 2013",
  "The answer is always yes and no. May 16, 2013",
  "Loneliness is the inability to find company in knowledge. Loneliness is not about people, it's about meaning. May 16, 2013",
  "Words use us to be spoken otherwise they would not exist. May 16, 2013",
  "The world divides into poets and poems. When you are a poet, what poem are you writing? And when you are a poem, who's writing you? May 15, 2013",
  "Children raise parents. May 3, 2013",
  "Life is plural. May 2, 2013",
  "There is a cosmic battle going on between time and space, and we are caught in the middle. When one wins, the world will end. Apr 17, 2013",
  "It is easy to confuse when and where. Apr 16, 2013",
  "We are almost certainly the leftovers. Apr 5, 2013",
  "Ideology is a study of causes, not of effects. Apr 2, 2013",
  "We can only fail. Just try to fail better. Apr 1, 2013",
  "Good can only triumph over Evil by employing extreme evil, thereby fulfilling the mission of Evil. Mar 31, 2013",
  "Life was obviously invented by a dead person. Mar 28, 2013",
  "It's not about where you are but about who's around you. Mar 26, 2013",
  "The present always feels premature even though the future is often overdue. Mar 25, 2013",
  "The only thing that is worse than not finding the solution to a problem is to find the right solution to the wrong problem. Mar 10, 2013",
  "Freedom fighters don't exist anymore: the only people willing to give their life for a cause are terrorists and soldiers. Mar 7, 2013",
  "The history of the world in a nutshell: the luxuries of the previous generation become the necessities of the new generation. Mar 7, 2013",
  "Science is not a catalog of certainties but an endless exploration of uncertainties. Mar 6, 2013",
  "How do imaginary objects travel through time and culture? Mar 5, 2013",
  "Do we live in the age of local globality or global locality? Jan 24, 2013",
  "I will not know who you are until you tell me who i am Jan 23, 2013",
  "Only by mourning our impotence can we assert our power. Jan 17, 2013",
  "Beauty is everywhere. Unfortunately, we are nowhere. Dec 30, 2012",
  "We think we are the protagonist of our life's story, but, by the end, we realize that we have merely been a supporting character in the biographies of everybody else. Dec 26, 2012",
  "Loneliness is a cancer only if you let it grow. Taken in small doses, it is the most powerful medicine, the only one capable of resurrecting a person. Dec 5, 2012",
  "The choice is not between being philosopher or not being philosophers, it's about being good or bad philosophers. Dec 5, 2012",
  "Let us not pretend otherwise: we are surrounded. Dec 3, 2012",
  "There is no apocalypse coming. We have been living inside the apocalypse ever since. We will disappear when it's over. Nov 19, 2012",
  "Nothing is trivial in history. Nov 13, 2012",
  "Life might not be worth living but neither is death worth dying. Nov 13, 2012",
  "No matter how fast you run, the distance remains the same. Nov 8, 2012",
  "Every minute makes sense to the minute after it but not to the minute before it, Nov 3, 2012",
  "History has been shaped by people who knew what Jesus, Mohammed, Buddha, etc really meant regardless of what they actually said",
  "My guess is that the greatest unhappiness would be a utopian world in which everybody is equally happy. Oct 15, 2012",
  "Sadly, psychologists (and society at large) think of solitude as a disease instead of a magical experience that helps you become you Oct 12, 2012",
  "It is becoming increasingly difficult to disappear Oct 12, 2012",
  "I don't want technology to keep me alive forever, i want technology to multiply me so that many copies of me can multitask on many projects at the same time Oct 7, 2012",
  "Philosophy is the discipline of turning solutions into problems, science is the discipline of turning problems into other problems, and art is the discipline of turning anything into a problem Sep 14, 2012",
  "If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a marketing commercial to sell ducks Sep 3, 2012",
  "You are a question that is never asked Aug 27, 2012",
  "One of the most difficult (and consequential) things in life is figuring out whether a question is stupid or not. Aug 11, 2012",
  "You are what you read. Make sure you want to be what you read.",
  "You should contradict yourself at least once a day. Jul 31, 2012",
  "We often forget that there are two alternatives to bad: good and worse. Jul 26, 2012",
  "Send me a copy of your past Jul 25, 2012",
  "Human civilization, from the Pyramids to the iPhone, is the story of turning the impossible into the inevitable (and a lot of it is not about genius but simply about education) Jul 24, 2012",
  "If i am the question, you are the answer (Remix: if the question is me, the answer is you). Jul 16, 2012",
  "Most people you meet have jobs that you are happy you don't have. Most people think the same of you. Jun 14, 2012",
  "Machines don't think, they do something else. Machine intelligence is as much an oxymoron as human furniture. Jun 7, 2012",
  "Machines must be understood not programmed. Jun 7, 2012",
  "We are not what we are. Now the question is: are we what we are not? Jun 6, 2012",
  "Silence is our shared vocabulary; not the silence of our voices, but the silence of their answers. Apr 10, 2012",
  "If i am stupid, i am not intelligent enough to realize it. Apr 9, 2012",
  "Most of the interesting thoughts of the world will never be tweeted. Apr 8, 2012",
  "The human race is a basement full of old scratched warped records: whenever you play one, you end up listening more carefully to the noise than to the music. Mar 12, 2012",
  "We are meaningful contradictions that give meaning to the meaningless contradictions of the universe (including ourselves) Feb 3, 2012",
  "Longevity made a huge difference for civilization: it takes about 20 years for the human brain to fully develop and become creative and the life expectancy of early humans was about 20. Jan 27,2012",
  "We should always remember that whatever we think about the brain is coming from our brain. Jan 23, 2012",
  "I observe the universe aware that it knows me a lot better than i know it, but nonetheless certain that what we are prevails over what it is. Jan 23, 2012",
  "Predictions about the future are always about what will happen (eventually). It would be much harder to predict what will never happen. Jan 2012",
  "Thinking about nothing makes it something. Thinking about something makes it nothing. Jan 2012",
  "There is an infinite number of possible DNA combinations that yield conscious beings. Will they all exist? More than once? Some never will? Dec 2011",
  "The sexual behavior of plants displays a mindblogging variety, from hermaphrodite flowers to subterranean sex of aspen. Even ordinary grasses, of which there are dozens, employ the most bizarre strategies to mate. Dec 2011",
  "Art has to be misunderstood by society in order to be great art. Nov 2011",
  "The metabolism of the vegetable world yields beautiful flowers, delicious fruits and nutritious nuts, and, at worst, dead leaves. The metabolism of the animal world yields disgusting stinking excrements.",
  "Evolution did not design us to believe only true facts, nor to buy only useful products, nor to say only meaningful sentences. Oct 18, 2011",
  "High-tech has become the discipline of complicating simple things. Oct 4, 2011",
  "Maps and clocks are the human equivalent of spiderwebs. Sep 13, 2011",
  "The most amazing thing about the laws of nature is that you don't need to know them in order to survive. In fact, nobody knows them - science is just an endless approximation. Sep 12, 2011",
  "Only when the tide recedes do you find out who's been swimming naked (Warren Buffet). We're all naked (piero) July 21, 2011",
  "Physics is an illusion. What it reveals is the structure of our brain, not the structure of the universe. July 12, 2011",
  "The world is divided into the ordinary and the extraordinary. The problem is deciding which is which. July 7, 2011",
  "What we understand is not enough to understand why we understand it. July 7, 2011",
  "Since we came to this world we only heard lies. But it's the lies that make it interesting. The truth would devastate us. June 27, 2011",
  "The most powerful knowledge is the knowledge that induces people to radically change their concept of what knowledge is. June 22, 2011",
  "A man is infinitely more complicated than his thoughts (Paul Valery) A man is infinitely more complicated than his actions (piero) June 12, 2011",
  "We always forget that the longest living beings on this planet have no brain: trees and bacteria. June 2, 2011",
  "Opiate use increased 35%, cocaine 27%, cannabis 8.5%. Why do more and more people need to get high more and more often? June 2, 2011",
  "Why do we try to explain mysteries instead of cherishing them? May 2, 2011",
  "Principles of Covariant Wisdom Apr 20, 2011",
  "Success in solving a set of problems inevitably creates a new set of problems, and a system that is incapable of solving the new set of problems. Apr 7, 2011",
  "Is there an end to science? Science is not a catalog of certainties but an endless exploration of uncertainties. Feb 21, 2011",
  "It has become cheaper to produce/accumulate information than to understand it. Feb 21, 2011",
  "Time is the thing that acts on all the things that do not act on themselves. 7:36 PM Feb 17, 2011",
  "The severity of a problem increases exponentially with the time it takes to realize that the severity of a problem increases exponentially with the time it takes to realize that the severity of a problem increases exponentially with the time it takes... . February 16, 2011",
  "Einstein was wrong: God did play dice with the Universe. The question is: who won?. February 13, 2011",
  "Would the world be a better place if everybody shared the same opinion, e.g. if everybody agreed with you on everything? December 27, 2010",
  "We keep changing the question but the answer remains the same. December 26, 2010",
  "We change so much that we become the change to which we have to adapt. December 21, 2010",
  "In 1894 Ubu, an imaginary character, invented Pataphysics, the science of imaginary solutions. Someone should invent a new science to study imaginary problems. And the real problems caused by their solutions. December 15, 2010",
  "The world may be simpler than the brain that conceives it. December 9, 2010",
  "The scientific paper with the best title ever probably was Does The Flap Of A Butterfly's Wings In Brazil Set Off A Tornado In Texas? (Ed Lorenz, 1972) but few people noticed the effect that the paper itself had: thousands of papers and books and tv shows have been made that mimic that title. Just like the butterfly that set off the tornado. So the paper can actually be read as a prophecy about itself. November 12, 2010",
  "Real beings dream unreal worlds. Do unreal beings dream the real world? November 10, 2010",
  "A comedian is someone who tells the truth. Truth is the set of all jokes told by all comedians in the world.September 21, 2010",
  "Consciousness's drive to total knowledge will eventually create a universe in which everything is alive and conscious and in which every conscious being is eating other conscious beings in order to survive; a world of pure cannibals.11:22 AM Aug 12th",
  "The difference between forever and never is both forever and never. 10:17 PM Aug 3rd , 2010",
  "The next time you say forever think of never.July 21, 2010, 2010",
  "We are overrated.7:00 PM Jul 7th , 2010",
  "Nature is a vast cemetery. Jun 13, 2010",
  "Civilization is self-organizing creativity that eventually transforms itself into organized mediocrity.May 26th, 2010",
  "Thankfully we cannot understand the universe. Can the universe understand us? 7:23 PM May 3rd , 2010",
  "It is difficult to make sense of other people because they are trying to make sense of me, so the sense changes all the time. 8:48 AM Apr 27th , 2010",
  "We speak as if we were one soul in one universe instead of multitudes of yesterdays in waterfalls of emptiness 8:12 PM Apr 2nd , 2010",
  "We are swimming in the lake in which future generations will drown. 1:33 AM Mar 10th , 2010",
  "Biologists realized the living organisms are feedback systems only after engineers realized that machines are feedback systems (1949) 8:22 PM Mar 1st , 2010",
  "History is the impossible becoming inevitable. 4:13 PM Feb 19th , 2010",
  "The meaning of life is the loss of meaning. We are programmed to find meaning in the loss of meaning. 5:20 PM Feb 17th , 2010",
  "Our brain tries to make sense of decay/erosion in terms of rebirth, metamorphosis, cycles, but decay is actually irreversible. 5:19 PM Feb 17th , 2010",
  "Processes of decay and erosion rule the universe. 5:19 PM Feb 17th , 2010",
  "11:05 PM Jan 24th 2010 Does an easier method to find information increase or decrease the motivation to discover new information?",
  "11:00 PM Jan 24th 2010 Globalization means the extinction of the other.",
  "10:59 PM Jan 24th 2010 Art was function in ancient times, representation in Greece, exploration in the renaissance, creation for the romantics, and now discovery",
  "11:37 PM Jan 21st 2010 The part is the sum of its wholes.",
  "11:19 PM Jan 21st 2010 If we could get rid of the customers, there would be a lot more successful startups with a lot more creative products.",
  "3:29 PM Jan 20th 2010 Knowledge is overrated, truth is underrated.",
  "11:35 AM Jan 20th 2010 Knowledge is depreciating at an accelerating pace",
  "10:11 PM Jan 18th 2010 If we assume that what we cannot explain does not exist, then we have understood everything - philosophy becomes the science of inexistence",
  "10:10 PM Jan 18th 2010 Answers to most questions are trivial. A civilization may never find the answer to a question because it does not look in the right place.",
  "10:10 PM Jan 18th 2010 Intelligence is measured by the questions you ask not by the answers you find.",
  "10:09 PM Jan 18th 2010 There is also a cognitive closure for civilizations: there is a limit to what a civilization can know.",
  "10:09 PM Jan 18th 2010 The cognitive closure: there is a limit to what a mind can understand (to the questions it can answer).",
  "10:09 PM Jan 18th 2010 Is an era defined by the questions it asks or by the answers it provides?",
  "Jan 25, 2010 Certainty is a by-product of confusion",
  "Jan 17, 2010 The boundaries of my language are the boundaries of your world (paraphrasing Wittgenstein)",
  "8:34 PM Jan 16th , 2010 Philosophy is the art of turning solutions into problems",
  "12:27 AM Jan 13th 2010: Poetry is the art of listening to silence. Poetry then turns it into signs that other minds turn into voices.",
  "10:59 PM Jan 12th 2010: Silence is the sound of wisdom. Nothing speaks louder than silence. Nature is always silent.",
  "10:58 PM Jan 12th 2010: Marie Curie said that the more we understand the less we fear. I think she got it all wrong: the more we know, the more we fear.",
  "11:51 AM Jan 12th 2010: Einstein said that humankind cannot solve its problems at the same level of consciousness from which we created them",
  "11:27 AM Jan 12th 2010: Adolf Wolfli,a patient in a madhouse, compiled an imaginary autobiography of 25000 pages, 1600 drawings, 1500 collages and 100s of songs.",
  "12:52 AM Jan 8th 2010: Doctor Faustroll was born in 1898 in Circassia at the age of 63 and died the same year at the same age",
  "8:00 PM Dec 25th, 2009 In a dictatorship the people are forced to consent. In a democracy the people are free to dissent. The media play opposite roles.",
  "8:00 PM Dec 25th, 2009 I am thinking of a whole number between 1 and 2.",
  "3:15 PM Dec 25th, 2009 The devil is in the details. Probably god too.",
  "4:22 PM Dec 18th, 2009 My existence is a message in itself. I am the reader, not the writer.",
  "8:32 PM Dec 16th, 2009 I swim into myself: i am the sea, not the swimmer. Or maybe both.",
  "8:27 PM Dec 16th, 2009 Or maybe i am both the hiker and the trail.",
  "8:27 PM Dec 16th, 2009 I crawl on myself: i am the trail, not the hiker.",
  "5:04 PM Dec 4th, 2009 For thousands of years in all civilizations of the Earth the dominant art was Poetry.",
  "9:17 AM Nov 20th, 2009 More sophisticated laws simply create more sophisticated criminals.",
  "6:19 PM Nov 1st, 2009 Death is the simplest of all mysteries: to die is to have been.",
  "Humans argue about what is true and what is not true. Other animals don't have this problem. They fight over resources (food, land, sex), but not over truth. Oct 21st, 2009",
  "If life is a fight, the question is simple: how can we fight back when w don't know who it is that we are fighting?2:27 PM Oct 11th",
  "When they are not thirsty, they keep riding their horses through the desert, happy to be alone, counting their pathetic treasure of sand.9:45 PM Oct 10th",
  "Orphans of history, we test blindfolded the invisible foundations with our cane.5:47 PM Oct 3rd",
  "A comedy of clowns rehearsing each other's part and never performing the comedy in front of a real audience. We die before we can learn it.7:57 PM Sep 22nd",
  "We may have forgotten how to listen. 7:03 PM Sep 18th",
  "When we become adults, our minds have died but are still unburied. The purpose of adult life is to give them a proper burial.9:19 PM Aug 22nd",
  "We build smarter and smarter machines, and dumber and dumber minds. It is inevitable that machines will become more intelligent than minds. Aug 21",
  "We have invested less and less in minds, because we don't need them as much as we used to.",
  "Will the post-computer age be about minds simulating computers? Aug 21",
  "The fact that each of us is a different universe sounds wonderful but could be the reason why it is so difficult to coexist.5:59 PM Aug 7th",
  "We think we know where we live, but we only live where we know.3:08 PM Aug 4th",
  "We are literally out of touch with our planet, not to mention with the rest of the universe (that we will never experience).3:07 PM Aug 4th",
  "It is the pursuit of happiness that makes people unhappy.10:29 PM Jul 28th",
  "To become moral animals, Robert Wright wrote, humans must first realize how thoroughly amoral they are.10:24 AM Jul 28th",
  "Academia bureaucratizes creativity.9:40 AM Jul 23rd",
  "Are there unnatural things? If yes, are they good or bad? Are civilizations unnatural?Are laws unnatural?9:28 AM Jul 23rd",
  "Does life always self-destroy, everywhere in the universe?4:06 PM Jul 22nd",
  "It is getting easier and easier for human society to destroy the planet. The odds that we will succeed increase with technological progress.10:53 AM Jul 21st",
  "Whatever we end up doing, even if we destroy the whole planet, it's in our genes, and therefore it's natural.10:46 AM Jul 21st",
  "Most animals protect themselves from change; they fear change. Humans instead cause it. We value originality, exploration, innovation.8 minutes ago",
  "We value exploration and innovation, i.e. new things. What is the survival advantage of new things?Wouldn't it be safer to stick to the old? Jul 20",
  "Is it genetic that we tend to think of original thinkers as superior people? What is the biological value of originality?4:16 PM Jul 13",
  "As a race, what makes us the same is what sets us apart: evil.3:44 PM Jul 8",
  "The closer one looks at the context the more diluted evil becomes. Evil acts are not the deed of one man but the product of a civilization.12:50 PM Jul 8",
  "If it's the intention that defines evil, then the more rational a decision is the more evil it can be; the more irrational the less evil.12:36 PM Jul 8",
  "We could not agree whether evil is extreme madness or extreme rationality. Western law considers madness an extenuating circumstance.12:35 PM Jul 8",
  "Maybe the ultimate evil is to deny that evil exists and pretend that there are always justifications for what happen, as historians do.9:50 AM Jul 8",
  "What makes it immoral if you lose and not immoral if you win? (Robert McNamara, about exterminating civilians in wars)4:15 PM Jul 7",
  "I discovered a new route to reach the top of the second highest mountain in California. Why are we proud of exploring and discovering?10:28 AM Jul 7",
  "We are a noise surrounded by silence; and it's the silence that truly defines what we are.10:06 AM Jul 2nd",
  "The production of souls is more important than the production of tanks (Stalin, 1932). 9:36 AM Jun 29",
  "The fiction of our science is the psychology of our religion.2:58 PM Jun 27",
  "No matter how far we look, we only see finite things existing for finite eras; and still we believe that the infinite exists. 2:43 PM Jun 26",
  "What is a telescope to blind people? That's what technology is to people with no imagination. 2:42 PM Jun 26",
  "If we thought more highly of ourselves we would not watch bad films, read bad books and listen to bad music just because they are publicized 2:37 PM Jun 26",
  "Life is a question in the form of an answer.10:23 AM Jun 26",
  "Fear of the world created the gods that created the world that we fear.4:04 PM Jun 25",
  "Loneliness truly defines our age. 10:45 AM Jun 24",
  "Were we immortal, we would all commit suicide. Jun 23",
  "Modern western life has turned family into an option and friendship into a transient quality. Therefore the culture of loneliness, the need to organize spare time. June 23",
  "Removing the unpredictable from life means removing the very essence of the human experience. June 22",
  "Organized activities for singles have two drawbacks: they inevitably lead to loneliness later in life, and don't prepare people for it. June 22",
  "The list of happiest countries in the world consistently includes countries such as Finland that have a very high rate of suicides. June 22",
  "People need to organize their spare time when they live unhappy lives. The more unhappy the more desperate to find things to do.",
  "Humans argue about what is true and what is not true. I think other animals don't have this problem. June 22",
  "Life is not a journey, it is a destination. Maybe an infinitely distant point.",
  "The essence is absence.4:16 PM Jun 19",
  "Yesterday i wrote a note to myself that i should never write notes to myself. Jun 17th",
  "Eternity is the poetry of amnesia. Jun 17th",
  "Only silence truly exists. Jun 17th",
  "We are doomed not only to repeat history but to never understand our role in it. Jun 17th",
  "We can control space but not time. In order to control time, we have to die. Jun 17th",
  "When we go back to a place in space, it looks different. If i could go back to a moment in time, would it feel different? Would it still be me ? Jun 17th",
  "Beauty is not in the eye of the beholder but in the mind of the thinker Jun 12th",
  "The gap between reality and meaning in the digital age has increased. Jun 12th",
  "I hate what i love. I love what i hate. Jun 11th",
  "All knowledge is conditioned by the structure of the knower (Varela) Jun 11th",
  "For most people the most difficult thing is to be comfortable with themselves. Loneliness and silence are poetry to some, but hell to most. Jun 9th",
  "Ideologies are sets of beliefs that help us believe life is worth living. Jun 2nd",
  "Each of us is a lifelong project to build a coherent theory on top of a blatant contradiction May 30th",
  "We are, first and foremost, vast contradictions. May 30th",
  "We are what we find, not what we search. May 28th",
  "We come spinning out of nothingness scattering stars like dust (Iranian poet Rumi) May 27th",
  "Let the beauty of what you love be what you do (Jalal ad-Din Rumi) May 27th",
  "In the age of search engines, we are what we search. Or are we what we find? May 26th",
  "Mecca before Mohammed, where all religions were worshiped, was the ideal city.",
  "Creativity requires discontinuity.",
  "The society of gyms, movie theaters, salsa classes, is the opposite of a creative society. It's just killing time while waiting for death.about 1 hour ago",
  "Peace and wealth yield structured lives; ultimately, monotonous predictable lives.",
  "1% of the world owns 40% of the world's wealth. Who owns 40% of happiness? 40% of creativity? 40% of morality?",
  "We perceive subjects everywhere in Nature, when in fact there are only objects.",
  "As literacy spread, we stopped listening and started reading.",
  "Too many voices talking at the same time. We need better ears. We've invented tools to talk all the time but haven't improved the listening.4:40 PM May 19th",
  "The relationship between beauty and beholder is roughly the same as the relationship between a formula and a student who doesn't get it10:59 PM May 18th",
  "I travel a lot. I hike a lot in the wilderness. Is what I learn from there worth what I forget about here?11:36 PM May 13th",
  "Great civilizations are those that do NOT learn from the mistakes of past civilizations11:21 AM May 13th",
  "We are a noise surrounded by silence. And it's the silence that defines what we are. Nobody really pays attention to the noise except us.11:11 AM May 13th",
  "If you look close enough and long enough, everything is transparent.12:12 AM May 13th",
  "Very few things are inevitable in life, not even life itself.10:44 AM May 12th",
  "The USA is creating an idiot-proof society. Europe is creating a genius-free society.1:03 PM May 9th",
  "Make a point of listening to silence. The best stories are there.",
  "A skeptical physicist asked me what do art and science have in common? My answer: They both come from the same mind.7:37 PM May 5th",
  "Talent is overrated. Luck is underrated.",
  "We underestimate the ingenuity of idiots",
  "If we could measure it, we'd find that the vast majority of the world's creativity is in the slums and poor villages of the developing world.",
  "Nature is a poet that never uses the word 'I'",
  "I think the human race was not meant to have spare time: people don't know what to do with their spare time."
];
module.exports = quotes;
